### ISSUE TITLE
Add caching configuration to secret stores

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.security#137]
**Is your feature request related to a problem? Please describe.**
Currently, we provide several options to include secret stores in an extendible solution for different kinds of applications. What we do not yet provide is a easy way to include caching to the resulting secret store.

**Describe the solution you'd like**
Some way to include this during the `.ConfigureSecretStore()`. 
For example:

```csharp
.ConfigureSecretStore((config, stores) =>
{
    stores.WithCaching(cacheConfiguration, memoryCache);
})
```

**Describe alternatives you've considered**
None.

**Comment by tomkerkhove** [comment]
This feel more like a per-provider thing where it's up to the provider to decide:
1. If they want to support caching
2. How it needs to be configured

So I'd argue it's more of an addition to the Key Vault overloads. For example, makes no sense to add caching for environment variables and/or configuration as it might even only make it more complex.

**Comment by tomkerkhove** [comment]
But I might be missing the point maybe?

**Comment by stijnmoreels** [comment]
Yes, I see your point in making it a per-provider. Although, it feels a lot more consumer-friendly to extract it to the 'composite' provider than to provide it on every provider you see it useful (with then the risk that some are forgotton).
It would make the "built-up" more complex though, on per-provider basis. 
But maybe something like this could be created:

```csharp
.ConfigureSecretStore((config, stores) =>
{
    stores.AddCached(stores.AddAzureKeyVault(auth, config));
})
```

**Comment by stijnmoreels** [comment]
The result of previous approach, will still make sure that an `ICachedSecretProvider` is registered in the DI, but we have to re-design then the `SecretStoreSource` model to take into account cached providers.

**Comment by tomkerkhove** [comment]
Frankly I think it makes it more complex and it should be defined per provider if they want to provide it and make sense. If it is the case, it's up to them to add it as an overload which can be as simple as `allowCaching: true`.

If we'll add this for all you'll get in tricky scenarios where secrets from configuration are cached while you only want it for Key Vault.

But it might be just me. Thoughts @fgheysels @wseye @gverstraete @MassimoC @mbraekman

**Comment by stijnmoreels** [comment]
Ah, yes, I see. I can agree with this. Although, we'll see how the `allowCaching: true` can maybe made into something else, or an overload of `.AddProvider`.

**Comment by stijnmoreels** [comment]
But good indeed to ask opinions on this.

**Comment by tomkerkhove** [comment]
> Ah, yes, I see. I can agree with this. Although, we'll see how the `allowCaching: true` can maybe made into something else, or an overload of `.AddProvider`.

For me using .AddProvider should be an exception since every provider should provide convenient methods to setup everything that is required for us, similar to what `AddAzureKeyVaultWithManagedServiceIdentity` does.

Another thing to keep in mind is that this impacts usage meaning how do we react if somebody wants to use `ICachedSecretProvider`?

Does it consult providers without caching or not? I'd argue yes because it's a best effort approach; but that's just me.

**Comment by stijnmoreels** [comment]
Yes, I would call providers that are not configured for caching during a cached operation of `ICachedSecretProvider`.

**Comment by mbraekman** [comment]
The way I see it, I wouldn't include any additional caching-logic in the secretStore itself, but make use of the `ICachedSecretProvider`.

What I'm getting at is, perhaps include a property `enableCaching: true` when adding an `ISecretProvider` to the secretStore, which in the back converts this provider into an `ICachedSecretProvider` with a default caching-configuration.

Then again, if a user wants to enable caching, why not leave it up to him/her to directly add an `ICachedSecretProvider` instead of an `ISecretProvider` to the store? 

But I could be missing something of course..

**Comment by stijnmoreels** [comment]
Now all that rest us is update the docs after or during #134 .
