### ISSUE TITLE
Remove obsolete types in v0.x

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.security#95]
Remove obsolete types in v0.x and ship v1.0 given this is causing issues and we should get rid of this legacy.

Related to #94

**Comment by tomkerkhove** [comment]
FYI @stijnmoreels discussed this with @fgheysels as it's causing some issues so we'd better just bite the bullet.

@fgheysels was so kind to pick this up!

**Comment by tomkerkhove** [comment]
The PR will be good to see what we are breaking so we can add it to our release notes

**Comment by fgheysels** [comment]
Should obsolete methods be removed as well ? For instance the async methods that are not suffixed with `Async` or should we limit ourselves to the obsolete types ?

**Comment by fgheysels** [comment]
While I'm having a look at the code, I couldn't help but notice something that I find a bit odd, and that's the structure of some interfaces and their implementations.

IMHO, it feels more natural to have more specific types 'deeper' in the namespace hierarchy and more general types at least on the same level as the specific types or have them a few levels up in the hierarchy.

To give a concrete example:
The `CertificateBasedAuthentication` type is now in the namespace `AzureKeyVault.Authentication`.  This class implements the `IKeyVaultAuthentication` interface and that interface can be found in the `AzureKeyVault.Authentication.Interfaces` namespace.
I do think that it is more natural if the interface type can be found 'earlier' in the hierarchy and the implementations of that interface up in the hierarchy (or at the same level).  (In this case, I'd put them in the same namespace).

Would love to hear your input on this.

**Comment by tomkerkhove** [comment]
I do not have a preference for the namespace so happy to change that. What do you think @stijnmoreels?

In terms of clean-up, we should remove everything that is marked obsolete - Types & methods.

@stijnmoreels Anything else you'd like to clean up?

We could draft a list of things to discuss and go through them with us 3 if you think it's interesting @fgheysels.

**Comment by stijnmoreels** [comment]
I agree that the location of the types (across all repo's btw) is not entirely something I find natural. Interfaces are on a diff namespace as the implementations and even the types used in those interfaces are in another namespace. All the repo's were already structured in a way **by type** instead of **by domain** which leads to `.Interfaces`, `.Models`, `Services`, ... folders instead of `.Authentication`, `.Secret`, ...
It doesn't seemed right at the time for my to deviate from this path for consistency reasons, but again, was never something I find natural, logical or even dev-friendly.

**Comment by fgheysels** [comment]
I agree with the fact that grouping types by 'type' is not a good idea since you indeed want to group your types more per functionality.   In another project we have seen the same 'by type' structure and decided to re-organize it per domain/functionality.   It was quite an effort, but now we've ended up with a codebase that feels more natural / logical.

(next to that, I also feel that there are many projects with few types, which would lead to many assemblies with few types wich I personally do not like either :) ).

**Comment by tomkerkhove** [comment]
Once the other PR is closed we can create one with your ideas and evaluate it maybe?

The reason for seperate projects is that they result in seperate NuGet packages. It's currently structured to not be focused only for Key Vault in case we want to add some other provider, but always open for suggestions.

**Comment by fgheysels** [comment]
We should indeed evaluate this and keep that discussion out of this issue.

**Comment by tomkerkhove** [comment]
Can you pick this up after #100 please @stijnmoreels ?

**Comment by stijnmoreels** [comment]
> Can you pick this up after #100 please @stijnmoreels ?

Yep, if you merge my PR for that (no write-access yet)
